### ISSUE TITLE
All com.android.support libraries must use the exact same version specification 

### ISSUE THREAD

**Issue by thanos04** [chat-sdk/chat-sdk-android#143]
Hello, I got the following error in build.gradle (module:app):

All com.android.support libraries must use the exact same version specification (mixing versions can lead to runtime crashes). Found versions 25.3.1, 23.0.0. Examples include com.android.support:animated-vector-drawable:25.3.1 and com.android.support:support-v13:23.0.0 less... (Ctrl+F1) 
There are some combinations of libraries, or tools and libraries, that are incompatible, or can lead to bugs. One such incompatibility is compiling with a version of the Android support libraries that is not the latest version (or in particular, a version lower than your targetSdkVersion.)

I tried searching online but I could not find any suitable resolutions. Any help would be greatly appreciated.

Thanks,

Al

**Comment by bensmiley** [comment]
This is fixed in v4.0.

**Comment by bensmiley** [comment]
I think the build tools version should be 27.0.2. I'll update the readme.

**Comment by jmp00000001** [comment]
Hi, awesome fast response! :)

I tried 27.0.2 and also (android studio recommended it) 27.0.3 
Still the same message

**Comment by bensmiley** [comment]
Can you post your `build.gradle` files?

**Comment by jmp00000001** [comment]
These are the minified gradle files (closed source) which still trigger the message (I also changed the appcompat-v7 version to 27.0.2 to match the compileSdkVersion):

############ Top level gradle file ############ 
```
buildscript {
     repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.3'
        classpath 'com.google.gms:google-services:3.1.0'
    }
}

allprojects {
    repositories {
        jcenter()
    }
}

```
############ App module gradle file ############
```
apply plugin: 'com.android.application'

// https://plus.google.com/u/0/+MarcReichelt/posts/BX2he4vSJaM
def getNumberOfGitCommits() {
    return 'git rev-list --count HEAD'.execute().text.trim().toInteger()
}

// https://plus.google.com/u/0/+MarcReichelt/posts/BX2he4vSJaM
def getCurrentGitHash() {
    return 'git rev-parse --short HEAD'.execute().text.trim()
}

android {
    compileSdkVersion 27
    buildToolsVersion "27.0.2"

    defaultConfig {
        applicationId "com.secret.appname"
        minSdkVersion 17
        targetSdkVersion 27
        versionCode getNumberOfGitCommits()
        resValue "string", "app_git_hash", getCurrentGitHash()
        versionName "1.0.0"
    }
}

repositories {
    maven { url "http://dl.bintray.com/chat-sdk/chat-sdk-android" }
    maven { url "https://maven.google.com" }
    maven { url "https://jitpack.io" }
}


dependencies {
    compile 'com.android.support:appcompat-v7:27.0.2'
    compile 'co.chatsdk.chatsdk:chat-sdk-core:4.0.8'
    compile 'co.chatsdk.chatsdk:chat-sdk-ui:4.0.8'
    compile 'co.chatsdk.chatsdk:chat-sdk-firebase-adapter:4.0.8'
    compile 'co.chatsdk.chatsdk:chat-sdk-firebase-file-storage:4.0.8'
}

apply plugin: 'com.google.gms.google-services'
```

**Comment by AkashGalani** [comment]
Go to project/.idea/libraries folder on your file system and see which libraries are different.
You will have to manually include these libraries with the same version in your build.gradle file.
Then, sync your project.

Example [Here](https://icetutor.com/question/all-com-android-support-libraries-must-use-the-exact-same-version-specification/)
